### PR TITLE
#174566602  Setup eslint to lint codebase

### PR DESCRIPTION
**Pull request by Augusta-E**
### What does this PR do?
This PR configures Eslint to lint codebase

### Description of tasks to be completed?
• install eslint, eslint-config-airbnb-base and eslint-plugin-import
• create .eslintrc.json file and add configurations

### How should this be manually tested/checked?
• Clone the PR
• Cd into the branch `ch-eslint-setup-174566602`
• Install the devDependencies using npm install

### What are the relevant pivotal tracker stories?
[#174566602](https://www.pivotaltracker.com/n/projects/2463429/stories/174566602)

### CODE REVIEW

**Review by bellogo — APPROVED** [review]
eslint works as expected

**Review by Extremophile-ai — APPROVED** [review]

**Review by Fiyin-Anne — APPROVED** [review]

**Review by codeliezel — APPROVED** [review]
Good job

**Comment by Augusta-E** [comment]
> Good job
> 
> @Augusta-E send another commit that follows the convention!!
> Add more to your PT description and lables

ok, thanks

**Review by Fiyin-Anne — APPROVED** [review]

**Review by donaldcrane — COMMENTED** [review]
in your descriptions use backticks to signify codes

**Comment by Augusta-E** [comment]
> in your descriptions use backticks to signify codes

Done, thanks. please approve if you are okay with it now

**Review by codeliezel — APPROVED** [review]
Great!

**Pull request merged**
