### PR TITLE
#174626824 Create comment and newsletter models

### PR DESCRIPTION
**Pull request by Fiyin-Anne**
#### What does this PR do

This PR creates migrations and seeders for comment and newsletter models.

#### Description of tasks to be completed?

- create comment model
- create comment migrations
- create comment seeders
- create newsletter model
- create newsletter migrations
- create newsletter seeders

#### How should this be manually tested/checked?

1. Clone the PR using `git fetch origin pull/29/head:ft-comment-newsletter-model-174626824`
2. Cd into the branch `ft-comment-newsletter-model-174626824`
3. Install the dependencies using `npm install`
4. Set up database connection string as shown in the `.env.sample` file.
5. Create `newsletter` and `comment` tables by running `npm run migrate`
6. Add data to the `newsletter` and `comment` tables by running `npm run seed`

#### What are the relevant pivotal tracker stories?
[#174626824](https://www.pivotaltracker.com/story/show/174626824)

### CODE REVIEW

**Review by md-codes — DISMISSED** [review]

**Comment by Augusta-E** [comment]
Great work, please add Id in your both seeders, use .query and .then in your migration instead of await

**Comment by Fiyin-Anne** [comment]
> Great work, please add Id in your both seeders, use .query and .then in your migration instead of await

Thanks, I'll fix that

**Review by Augusta-E — DISMISSED** [review]

**Review by md-codes — DISMISSED** [review]
Everything works fine, good job 👍

**Review by md-codes — APPROVED** [review]

**Review by codeliezel — APPROVED** [review]
Good job

**Review by md-codes — APPROVED** [review]

**Review by Augusta-E — APPROVED** [review]

**Pull request merged**
